const ACTIONS = {
  WRITE_COINS_GLOBAL_TO_DB: "WRITE_COINS_GLOBAL_TO_DB",
  WRITE_COINS_HOURLY_TO_DB: "WRITE_COINS_HOURLY_TO_DB",
  GET_COINS_DB: "GET_COINS_DB",
  GET_GLOBAL_DB: "GET_GLOBAL_DB",
}

module.exports = { ACTIONS };