const ACTIONS = {
  WRITE_COINS_GLOBAL_TO_DB: "WRITE_COINS_GLOBAL_TO_DB",
  WRITE_COINS_HOURLY_TO_DB: "WRITE_COINS_HOURLY_TO_DB",
  GET_COINS_DB: "GET_COINS_DB",
  GET_GLOBAL_DB: "GET_GLOBAL_DB",
  STORE_COIN_CHARTS: "STORE_COIN_CHARTS",
  GET_COIN_CHARTS: "GET_COIN_CHARTS",
  UPDATE_BATCH_COINS: "UPDATE_BATCH_COINS",
  GET_BATCH_COINS: "GET_BATCH_COINS",
}

module.exports = { ACTIONS };